### ISSUE TITLE
トップページに関連する処理をするMOE2 Clientを作る

### ISSUE THREAD

**Issue by KarmaMi** [KarmaMi/diplomacy-moe2-plugin#6]
#4が巨大issueとなりそうなので，分割した

# 要件
* [ ] 常にアクセス可能
* [ ] 更新可能
    * ログイン状態の変更時は必ず更新する
* [ ] ログイン，ログアウト，ID取得ができる
* [ ] ID情報を参照することができる
* [ ] 募集中卓の情報を表示できる
* [ ] 進行中卓の情報を表示できる
* [ ] 終了済卓の情報表示を行うことができる
* [ ] 卓を作成することができる
* [ ] 卓情報を見ることができる
* [ ] 広告等その他の必要な情報を取得できる

# TODO
## テストデータの作成
* [ ] トップページ(ログアウト，ログイン，ログインかつ参加中)の3パターンのデータを作る．
* [ ] ID作成，ログインのテストデータを作る．
* [ ] 卓に参加するときのページをKeyword付きの場合を含めてテストデータを作る．
* [ ] 卓を作成する際(出来ない時，できる時)のテストデータを作る．
* [ ] 終了済卓一覧のテストデータを作る

## 実装
* [ ] トップページのパーサを作る
* [ ] トップページで完結するAPIを作る
* [ ] その他のページへアクセスするAPIを作る
